#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 18 14:59:17 2018

@author: hannah
"""

import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv('/home/hannah/miniconda3/envs/vrdi/n_by_n/run5_18x18_unique_clustered_party_counts.csv', sep = ',', header = None, index_col = 0,quoting=2) 

total_votes = []

for i, row in data.iterrows():
    total_votes.append(row[13])

#print (total_votes)
    
plt.hist(total_votes, normed=True, bins=5)
plt.ylabel('Probability');